// src/lib/utils/slugify.ts
function transliterate(text: string): string {
    return text
        // Turkish characters
        .replace(/ğ/g, 'g')
        .replace(/Ğ/g, 'G')
        .replace(/ü/g, 'u')
        .replace(/Ü/g, 'U')
        .replace(/ş/g, 's')
        .replace(/Ş/g, 'S')
        .replace(/ı/g, 'i')
        .replace(/İ/g, 'I')
        .replace(/ö/g, 'o')
        .replace(/Ö/g, 'O')
        .replace(/ç/g, 'c')
        .replace(/Ç/g, 'C')
        // Other common characters
        .replace(/á|à|â|ä|å/g, 'a')
        .replace(/Á|À|Â|Ä|Å/g, 'A')
        .replace(/é|è|ê|ë/g, 'e')
        .replace(/É|È|Ê|Ë/g, 'E')
        .replace(/í|ì|î|ï/g, 'i')
        .replace(/Í|Ì|Î|Ï/g, 'I')
        .replace(/ó|ò|ô|ö|ø/g, 'o')
        .replace(/Ó|Ò|Ô|Ö|Ø/g, 'O')
        .replace(/ú|ù|û|ü/g, 'u')
        .replace(/Ú|Ù|Û|Ü/g, 'U')
        .replace(/ý|ÿ/g, 'y')
        .replace(/Ý|Ÿ/g, 'Y')
        .replace(/ñ/g, 'n')
        .replace(/Ñ/g, 'N')
        .replace(/ß/g, 'ss')
        .replace(/æ/g, 'ae')
        .replace(/Æ/g, 'AE')
        .replace(/œ/g, 'oe')
        .replace(/Œ/g, 'OE')
        // Cyrillic characters (basic)
        .replace(/а/g, 'a')
        .replace(/А/g, 'A')
        .replace(/б/g, 'b')
        .replace(/Б/g, 'B')
        .replace(/в/g, 'v')
        .replace(/В/g, 'V')
        .replace(/г/g, 'g')
        .replace(/Г/g, 'G')
        .replace(/д/g, 'd')
        .replace(/Д/g, 'D')
        .replace(/е/g, 'e')
        .replace(/Е/g, 'E')
        .replace(/ё/g, 'yo')
        .replace(/Ё/g, 'Yo')
        .replace(/ж/g, 'zh')
        .replace(/Ж/g, 'Zh')
        .replace(/з/g, 'z')
        .replace(/З/g, 'Z')
        .replace(/и/g, 'i')
        .replace(/И/g, 'I')
        .replace(/й/g, 'y')
        .replace(/Й/g, 'Y')
        .replace(/к/g, 'k')
        .replace(/К/g, 'K')
        .replace(/л/g, 'l')
        .replace(/Л/g, 'L')
        .replace(/м/g, 'm')
        .replace(/М/g, 'M')
        .replace(/н/g, 'n')
        .replace(/Н/g, 'N')
        .replace(/о/g, 'o')
        .replace(/О/g, 'O')
        .replace(/п/g, 'p')
        .replace(/П/g, 'P')
        .replace(/р/g, 'r')
        .replace(/Р/g, 'R')
        .replace(/с/g, 's')
        .replace(/С/g, 'S')
        .replace(/т/g, 't')
        .replace(/Т/g, 'T')
        .replace(/у/g, 'u')
        .replace(/У/g, 'U')
        .replace(/ф/g, 'f')
        .replace(/Ф/g, 'F')
        .replace(/х/g, 'kh')
        .replace(/Х/g, 'Kh')
        .replace(/ц/g, 'ts')
        .replace(/Ц/g, 'Ts')
        .replace(/ч/g, 'ch')
        .replace(/Ч/g, 'Ch')
        .replace(/ш/g, 'sh')
        .replace(/Ш/g, 'Sh')
        .replace(/щ/g, 'shch')
        .replace(/Щ/g, 'Shch')
        .replace(/ъ/g, '')
        .replace(/Ъ/g, '')
        .replace(/ы/g, 'y')
        .replace(/Ы/g, 'Y')
        .replace(/ь/g, '')
        .replace(/Ь/g, '')
        .replace(/э/g, 'e')
        .replace(/Э/g, 'E')
        .replace(/ю/g, 'yu')
        .replace(/Ю/g, 'Yu')
        .replace(/я/g, 'ya')
        .replace(/Я/g, 'Ya')
        // Arabic characters (basic)
        .replace(/ا/g, 'a')
        .replace(/ب/g, 'b')
        .replace(/ت/g, 't')
        .replace(/ث/g, 'th')
        .replace(/ج/g, 'j')
        .replace(/ح/g, 'h')
        .replace(/خ/g, 'kh')
        .replace(/د/g, 'd')
        .replace(/ذ/g, 'dh')
        .replace(/ر/g, 'r')
        .replace(/ز/g, 'z')
        .replace(/س/g, 's')
        .replace(/ش/g, 'sh')
        .replace(/ص/g, 's')
        .replace(/ض/g, 'd')
        .replace(/ط/g, 't')
        .replace(/ظ/g, 'z')
        .replace(/ع/g, 'a')
        .replace(/غ/g, 'gh')
        .replace(/ف/g, 'f')
        .replace(/ق/g, 'q')
        .replace(/ك/g, 'k')
        .replace(/ل/g, 'l')
        .replace(/م/g, 'm')
        .replace(/ن/g, 'n')
        .replace(/ه/g, 'h')
        .replace(/و/g, 'w')
        .replace(/ي/g, 'y')
        // Greek characters (basic)
        .replace(/α/g, 'a')
        .replace(/Α/g, 'A')
        .replace(/β/g, 'v')
        .replace(/Β/g, 'V')
        .replace(/γ/g, 'g')
        .replace(/Γ/g, 'G')
        .replace(/δ/g, 'd')
        .replace(/Δ/g, 'D')
        .replace(/ε/g, 'e')
        .replace(/Ε/g, 'E')
        .replace(/ζ/g, 'z')
        .replace(/Ζ/g, 'Z')
        .replace(/η/g, 'i')
        .replace(/Η/g, 'I')
        .replace(/θ/g, 'th')
        .replace(/Θ/g, 'Th')
        .replace(/ι/g, 'i')
        .replace(/Ι/g, 'I')
        .replace(/κ/g, 'k')
        .replace(/Κ/g, 'K')
        .replace(/λ/g, 'l')
        .replace(/Λ/g, 'L')
        .replace(/μ/g, 'm')
        .replace(/Μ/g, 'M')
        .replace(/ν/g, 'n')
        .replace(/Ν/g, 'N')
        .replace(/ξ/g, 'ks')
        .replace(/Ξ/g, 'Ks')
        .replace(/ο/g, 'o')
        .replace(/Ο/g, 'O')
        .replace(/π/g, 'p')
        .replace(/Π/g, 'P')
        .replace(/ρ/g, 'r')
        .replace(/Ρ/g, 'R')
        .replace(/σ|ς/g, 's')
        .replace(/Σ/g, 'S')
        .replace(/τ/g, 't')
        .replace(/Τ/g, 'T')
        .replace(/υ/g, 'y')
        .replace(/Υ/g, 'Y')
        .replace(/φ/g, 'f')
        .replace(/Φ/g, 'F')
        .replace(/χ/g, 'ch')
        .replace(/Χ/g, 'Ch')
        .replace(/ψ/g, 'ps')
        .replace(/Ψ/g, 'Ps')
        .replace(/ω/g, 'o')
        .replace(/Ω/g, 'O')
        // Remove any remaining non-ASCII characters
        .replace(/[^\x00-\x7F]/g, '');
}

export function slugify(text: string): string {
    return transliterate(text)
        .toString()
        .toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^\w\-]+/g, '')
        .replace(/\-\-+/g, '-')
        .replace(/^-+/, '')
        .replace(/-+$/, '');
}

export function generateSlugs(title: string, existingSlugs: Set<string>): string {
    let baseSlug = slugify(title);
    let slug = baseSlug;
    let counter = 1;

    while (existingSlugs.has(slug)) {
        slug = `${baseSlug}-${counter}`;
        counter++;
    }

    return slug;
}